[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*", "crates/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.2.2"
hdk = "=0.1.2"
holochain_integrity_types = "=0.1.2"
serde = "1"

[workspace.dependencies.follows]
path = "dnas/mewsfeed/zomes/coordinator/follows"

[workspace.dependencies.follows_integrity]
path = "dnas/mewsfeed/zomes/integrity/follows"

[workspace.dependencies.likes]
path = "dnas/mewsfeed/zomes/coordinator/likes"

[workspace.dependencies.likes_integrity]
path = "dnas/mewsfeed/zomes/integrity/likes"

[workspace.dependencies.mews]
path = "dnas/mewsfeed/zomes/coordinator/mews"

[workspace.dependencies.mews_integrity]
path = "dnas/mewsfeed/zomes/integrity/mews"

[workspace.dependencies.profiles]
path = "dnas/mewsfeed/zomes/coordinator/profiles"

[workspace.dependencies.profiles_integrity]
path = "dnas/mewsfeed/zomes/integrity/profiles"

[workspace.dependencies.ping]
path = "dnas/mewsfeed/zomes/coordinator/ping"

[workspace.dependencies.mews_types]
path = "crates/mews_types"
