[package]
edition = "2018"
name = "index"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "index"

[dependencies]
serde = "1"
derive_more = "0"
chrono = {version = "0.4", features = ["serde"]}

hdk = {version = "0.0.120", features = ["encoding"]}

