[package]
name = "mews_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mews_integrity"

[dependencies]
hdi = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
prefix_index = { path = "../../../../../../holochain-prefix-index/lib/prefix_index" }
mews_types = { workspace = true }