[package]
edition = "2021"
name = "mews"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mews"

[dependencies]
serde = "1"
derive_more = "0"
chrono = {version = "0.4", features = ["serde"]}
regex = "1"

hdk = {version = "0.0.123", features = ["encoding"]}

