[package]
edition = "2018"
name = "filestore"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "filestore"

[dependencies]
serde = "1"
derive_more = "0"
chrono = {version = "0.4", features = ["serde"]}

hdk = "0.0.118"
holo_hash = { version = "0.0.15", features = ["encoding"] }
