[package]
edition = "2018"
name = "filestore"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "filestore"

[dependencies]
derive_more = "0"
serde = "1"

hdk = {version = "0.0.120", features = ["encoding"]}
